//+------------------------------------------------------------------+
//|	Project name:        IFJ - Team project                          |
//| Filename:            precedence.c                                |
//| Author:                                               			 |
//|	Encoding:            UTF-8										 |
//|	Description:         Source of Precendenc Table.				 |
//+------------------------------------------------------------------+
#include "precedence.h"


//precedentni tabluka
static int PTable[16][16];

//inicializace precedentnej tabulky
void PTableInit (int (*PTable)[16])
{
	PTable[EQUAL][ADD]= PTLESS;
	PTable[EQUAL][SUB]=	PTLESS;
	PTable[EQUAL][MUL]= PTLESS;
	PTable[EQUAL][DIV]= PTLESS;
	PTable[EQUAL][LBRACE]= PTLESS;
	PTable[EQUAL][DATATYPE]= PTLESS;
	PTable[EQUAL][IDF]= PTLESS;
	PTable[NOTEQUAL][ADD]= PTLESS;
	PTable[NOTEQUAL][SUB]= PTLESS;
	PTable[NOTEQUAL][MUL]= PTLESS;
	PTable[NOTEQUAL][DIV]= PTLESS;
	PTable[NOTEQUAL][LBRACE]= PTLESS;
	PTable[NOTEQUAL][DATATYPE]= PTLESS;
	PTable[NOTEQUAL][IDF]= PTLESS;
	PTable[LESSEQUAL][ADD]= PTLESS;
	PTable[LESSEQUAL][SUB]= PTLESS;
	PTable[LESSEQUAL][MUL]= PTLESS;
	PTable[LESSEQUAL][DIV]= PTLESS;
	PTable[LESSEQUAL][LBRACE]= PTLESS;
	PTable[LESSEQUAL][DATATYPE]= PTLESS;
	PTable[LESSEQUAL][IDF]= PTLESS;
	PTable[MOREEQUAL][ADD]= PTLESS;
	PTable[MOREEQUAL][SUB]= PTLESS;
	PTable[MOREEQUAL][MUL]= PTLESS;
	PTable[MOREEQUAL][DIV]= PTLESS;
	PTable[MOREEQUAL][LBRACE]= PTLESS;
	PTable[MOREEQUAL][DATATYPE]= PTLESS;
	PTable[MOREEQUAL][IDF]= PTLESS;
	PTable[LESS][ADD]= PTLESS;
	PTable[LESS][SUB]= PTLESS;
	PTable[LESS][MUL]= PTLESS;
	PTable[LESS][DIV]= PTLESS;
	PTable[LESS][LBRACE]= PTLESS;
	PTable[LESS][DATATYPE]= PTLESS;
	PTable[LESS][IDF]= PTLESS;
	PTable[MORE][ADD]= PTLESS;
	PTable[MORE][SUB]= PTLESS;
	PTable[MORE][MUL]= PTLESS;
	PTable[MORE][DIV]= PTLESS;
	PTable[MORE][LBRACE]= PTLESS;
	PTable[MORE][DATATYPE]= PTLESS;
	PTable[MORE][IDF]= PTLESS;
	PTable[ADD][MUL]= PTLESS;
	PTable[ADD][DIV]= PTLESS;
	PTable[ADD][LBRACE]= PTLESS;
	PTable[ADD][DATATYPE]= PTLESS;
	PTable[ADD][IDF]= PTLESS;
	PTable[SUB][MUL]= PTLESS;
	PTable[SUB][DIV]= PTLESS;
	PTable[SUB][LBRACE]= PTLESS;
	PTable[SUB][DATATYPE]= PTLESS;
	PTable[SUB][IDF]= PTLESS;
	PTable[MUL][LBRACE]=PTLESS;
	PTable[MUL][DATATYPE]=PTLESS;
	PTable[MUL][IDF]= PTLESS;
	PTable[DIV][LBRACE]=PTLESS;
	PTable[DIV][DATATYPE]=PTLESS;
	PTable[DIV][IDF]= PTLESS;
	PTable[LBRACE][EQUAL]= PTLESS;
	PTable[LBRACE][NOTEQUAL]= PTLESS;
	PTable[LBRACE][LESSEQUAL]= PTLESS;
	PTable[LBRACE][MOREEQUAL]= PTLESS;
	PTable[LBRACE][LESS]= PTLESS;
	PTable[LBRACE][MORE]= PTLESS;
	PTable[LBRACE][ADD]= PTLESS;
	PTable[LBRACE][SUB]= PTLESS;
	PTable[LBRACE][MUL]= PTLESS;
	PTable[LBRACE][DIV]= PTLESS;
	PTable[LBRACE][LBRACE]= PTLESS;
	PTable[LBRACE][RBRACE]= PTEQUAL;
	PTable[LBRACE][DATATYPE]=PTLESS;
	PTable[LBRACE][IDF]= PTLESS;
	PTable[LBRACE][TERMINAL]= PTNULL;
	PTable[RBRACE][LBRACE]= PTNULL;
	PTable[RBRACE][DATATYPE]= PTNULL;
	PTable[RBRACE][IDF]= PTNULL;
	PTable[IDF][LBRACE]= PTNULL;
	PTable[IDF][DATATYPE] = PTNULL;
	PTable[IDF][IDF]= PTNULL;
	PTable[DATATYPE][LBRACE]= PTNULL;
	PTable[DATATYPE][DATATYPE]= PTNULL;
	PTable[DATATYPE][IDF]= PTNULL;
	PTable[TERMINAL][EQUAL]= PTLESS;
	PTable[TERMINAL][NOTEQUAL]= PTLESS;
	PTable[TERMINAL][LESSEQUAL]= PTLESS;
	PTable[TERMINAL][MOREEQUAL]= PTLESS;
	PTable[TERMINAL][LESS]= PTLESS;
	PTable[TERMINAL][MORE]= PTLESS;
	PTable[TERMINAL][ADD]= PTLESS;
	PTable[TERMINAL][SUB]= PTLESS;
	PTable[TERMINAL][MUL]= PTLESS;
	PTable[TERMINAL][DIV]= PTLESS;
	PTable[TERMINAL][LBRACE]= PTLESS;
	PTable[TERMINAL][RBRACE]= PTNULL;
	PTable[TERMINAL][IDF]= PTLESS;
	PTable[TERMINAL][DATATYPE]= PTLESS;
	PTable[TERMINAL][TERMINAL]= PTNULL;

}
